- name: Variables from prompt level
  hosts: localhost
  vars_prompt: 
    - name: username
      prompt: "Pls enter username"
      private: false # to display in prompt 
    - name: password
      prompt: "Enter password"
      private: true # not to display at prompt
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: " username is {{username}} & pwd is {{password}}"