- name: Accessing the variables at inventory level #if no var is decalaried at any where ansible will check in inventory
  hosts: localhost
  tasks:
    - name: Inventory variables
      vars:
        course: "Ansible"
      ansible.builtin.debug:
        msg: "Hi I am learning {{course}} from {{trainer}}"
